PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS user_tipo (
    id SERIAL PRIMARY KEY,
    descrizione VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tipo INTEGER NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tipo) REFERENCES user_tipo(id)
);


CREATE TABLE IF NOT EXISTS emails(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS documenti(
    id SERIAL PRIMARY KEY,
    titolo VARCHAR(100) NOT NULL,
    contenuto TEXT NOT NULL,
    path VARCHAR(255) NOT NULL,
    autore_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (autore_id) REFERENCES users(id)
);
